---
title: "News and Press"
---

## 2026/09/02

We preprinted Prarthana's work on [mapping the genetic architecture of somatic passenger mutations at population-scale](https://www.medrxiv.org/content/10.64898/2026.08.21.26361040v1) 

## 2026/06/04

We presented our [work on novel forms of CH point mutations](https://www.medrxiv.org/content/10.1101/2025.10.12.25337792v2) at the Cancer Prevention Research Conference 

## 2026/05/19

Xuebo Wang (perturb-seq modeling) and Yikai Dong (centromere structural variation) presented our work at the STATGEN 2026 conference.

## 2026/05/07

We presented our [work on novel forms of CH point mutations](https://www.medrxiv.org/content/10.1101/2025.10.12.25337792v2) at the Biology of Genomes 2026 (talk).

## 2026/04/29

Yikai Dong and Prarthana Reddy presented our work during our "Research in Progress" seminar at the DOHG. 

## 2026/03/31

Congratulations to Xuebo Wang for his 2nd place finish for the Patek-Naik Award for pre-candidacy BIOS PhD students! Xuebo received the award for his outstanding research proposal. 

## 2026/02/09

Our [work on novel forms of CH  point mutations](https://www.medrxiv.org/content/10.1101/2025.10.12.25337792v2) was described in a recent [Cancer Discovery News](https://aacrjournals.org/cdnews/news/3019/Bringing-AI-to-Cancer-s-Regulatory-Genome) article on using AI to understand the regulatory genome in cancer.

## 2026/02/01

Sean Jones (GMB PhD student) joins the lab for a rotation. Welcome, Sean!

## 2026/01/05

 - Prarthana Sanjeeva Reddy joins the lab as Lead Research Specialist. Welcome!
 - Yikai Dong (GMB PhD student) joins the lab for a rotation. Welcome, Yikai!

## 2025/10/16

 - We presented our [work on novel forms of CH point mutations](https://www.medrxiv.org/content/10.1101/2025.10.12.25337792v1) at ASHG 2025 (platform talk)
 - Our [work](https://www.nature.com/articles/s41467-025-64236-x) on 'driverless' CH is now up at Nature Communications 

## 2025/9/28

Xuebo Wang presented our work on using genomic foundation models to infer gene regulatory networks at the DOHG retreat.

## 2025/7/22

We preprinted our [new polygenic risk score method](https://www.medrxiv.org/content/10.1101/2025.07.21.25331918v1) (with April Kim and Alexis Battle). 

## 2025/2/7

We presented our work on gene regulatory network inference in CD4 T cells to the [ENCORE group](https://encore-group.emory.edu/encore-hosts-invited-seminar-with-joshua-weinstock-on-gene-regulatory-networks/). 

## 2024/11/7

We presented our work on [clonal hematopoiesis without known drivers](https://www.medrxiv.org/content/10.1101/2024.08.22.24312319v2) at ASHG24, which received
a reviewers' choice award (top 10% of poster abstracts).  

## 2024/10/11

Our work on inferring gene regulatory networks in CD4+ T cells is now online at [Cell Genomics](https://www.cell.com/cell-genomics/fulltext/S2666-979X(24)00290-8)! 

## 2024/10/1

We extraordinarily fortunate to welcome three talented students to the lab:

### Master's students
 - Xuebo Wang

### Undergraduate students
 - Amber Zhou
 - Mingke Tian

## 2024/08/14

We've opened our doors at Emory! 