---
title: "Open positions"
---

<div style="text-align: center;">
  <strong>We are now open and hiring at all levels!</strong>
</div>

## PhD Students

We primarily work with students enrolled in the [Biostatistics and Bioinformatics program](https://sph.emory.edu/departments/bios/degree-programs/phd/index.html). Although our primary affiliation 
is in Human Genetics, we are still able to recruit BIOS students. 
Prospective students should have an interest in statistical 
genetics and genetic epidemiology. You are welcome to contact
Josh ahead of time, although admissions are centralized through the BIOS admissions committee. 


We are also affiliated with the Genetics and Molecular Biology (GMB) program. Please contact Josh if you are interested in a rotation. Note: this is a computational lab, and quantitative skills are highly valued. Tailored computational training programs are a possibility for enthusiastic students without a 
quantitative background. 

We are open to co-mentorship opportunities as well with other labs.

## Postdocs 

Your application should include a cover letter describing your interest in our work. It would be ideal to propose a specific project that aligns with our interests and is distinct from your previous work. Please include your CV and a list of references. 

Postdoc candidates should have a PhD in 
genetics, biostatistics, computer science, epidemiology, biomedical engineering, or similar. Candidates should have at least one first-author publication in a peer-reviewed journal. 

## Undergraduates

We are accepting applications from undergraduates with interests that align with our research program. Please contact Josh with your interests, and suggest an idea that you have for a project. 

## Our lab culture

We value a highly collaborative, interactive scientific environment, where cross-pollination of ideas from trainees in different disciplines is highly encouraged. We especially prioritize an inclusive, polite, and professional work culture. We have a mix of regular events, spanning lab meetings, journal clubs, and lab lunches and other social events. 